package org.jeecg.modules.workflow.flowable;

import org.flowable.engine.ProcessEngine;
import org.flowable.engine.impl.cfg.StandaloneInMemProcessEngineConfiguration;
import org.flowable.task.api.Task;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * Runs the BPMN generated by the simple designer through a real Flowable engine.
 * This deliberately does not boot Spring: the test focuses on native multi-instance
 * task creation and completion-condition semantics.
 */
class WorkflowMultiInstanceEngineTest {

    private final WorkflowSimpleModelConverter converter = new WorkflowSimpleModelConverter();
    private ProcessEngine processEngine;

    @AfterEach
    void tearDown() {
        if (processEngine != null) {
            processEngine.close();
        }
    }

    @Test
    void orSignCompletesAfterFirstApprovalAndCancelsRemainingInstances() {
        String xml = converter.convert("orSignEngine", "或签引擎测试", approval("OrSignApprove", 3, null));
        processEngine = engine();
        deploy(xml, "or-sign.bpmn20.xml");

        var instance = processEngine.getRuntimeService().startProcessInstanceByKey("orSignEngine",
                Map.of("_workflowTaskAssignees_OrSignApprove", List.of("u1", "u2")));
        List<Task> tasks = activeTasks(instance.getId());
        assertEquals(2, tasks.size());
        assertEquals(Set.of("u1", "u2"), tasks.stream().map(Task::getAssignee).collect(java.util.stream.Collectors.toSet()));

        processEngine.getTaskService().complete(tasks.get(0).getId());

        assertEquals(0, activeTasks(instance.getId()).size());
        assertNull(processEngine.getRuntimeService().createProcessInstanceQuery()
                .processInstanceId(instance.getId()).singleResult());
    }

    @Test
    void ratioSignKeepsProcessRunningUntilConfiguredRatioIsReached() {
        String xml = converter.convert("ratioEngine", "会签比例测试", approval("RatioApprove", 2, 60));
        processEngine = engine();
        deploy(xml, "ratio.bpmn20.xml");

        var instance = processEngine.getRuntimeService().startProcessInstanceByKey("ratioEngine",
                Map.of("_workflowTaskAssignees_RatioApprove", List.of("u1", "u2", "u3")));
        List<Task> tasks = activeTasks(instance.getId());
        assertEquals(3, tasks.size());

        processEngine.getTaskService().complete(tasks.get(0).getId());
        assertNotNull(processEngine.getRuntimeService().createProcessInstanceQuery()
                .processInstanceId(instance.getId()).singleResult());
        assertEquals(2, activeTasks(instance.getId()).size());

        processEngine.getTaskService().complete(activeTasks(instance.getId()).get(0).getId());
        assertEquals(0, activeTasks(instance.getId()).size());
        assertNull(processEngine.getRuntimeService().createProcessInstanceQuery()
                .processInstanceId(instance.getId()).singleResult());
    }

    @Test
    void sequentialApprovalCreatesOnlyTheNextInstance() {
        String xml = converter.convert("sequentialEngine", "顺序审批测试", approval("SequentialApprove", 4, null));
        processEngine = engine();
        deploy(xml, "sequential.bpmn20.xml");

        var instance = processEngine.getRuntimeService().startProcessInstanceByKey("sequentialEngine",
                Map.of("_workflowTaskAssignees_SequentialApprove", List.of("u1", "u2", "u3")));
        assertEquals(List.of("u1"), activeTasks(instance.getId()).stream().map(Task::getAssignee).toList());

        processEngine.getTaskService().complete(activeTasks(instance.getId()).get(0).getId());
        assertEquals(List.of("u2"), activeTasks(instance.getId()).stream().map(Task::getAssignee).toList());
        processEngine.getTaskService().complete(activeTasks(instance.getId()).get(0).getId());
        assertEquals(List.of("u3"), activeTasks(instance.getId()).stream().map(Task::getAssignee).toList());
        processEngine.getTaskService().complete(activeTasks(instance.getId()).get(0).getId());

        assertNull(processEngine.getRuntimeService().createProcessInstanceQuery()
                .processInstanceId(instance.getId()).singleResult());
    }

    private ProcessEngine engine() {
        return new StandaloneInMemProcessEngineConfiguration()
                .setJdbcUrl("jdbc:h2:mem:flowable_" + UUID.randomUUID().toString().replace('-', '_'))
                .setDatabaseSchemaUpdate("create")
                .setAsyncExecutorActivate(false)
                .buildProcessEngine();
    }

    private void deploy(String xml, String resourceName) {
        processEngine.getRepositoryService().createDeployment()
                .addString(resourceName, xml)
                .deploy();
    }

    private List<Task> activeTasks(String processInstanceId) {
        return processEngine.getTaskService().createTaskQuery()
                .processInstanceId(processInstanceId).active().list();
    }

    private Map<String, Object> approval(String id, int approveMethod, Integer approveRatio) {
        Map<String, Object> approval = new LinkedHashMap<>();
        approval.put("id", id);
        approval.put("name", "审批");
        approval.put("type", 11);
        approval.put("candidateStrategy", 30);
        approval.put("candidateParam", List.of("u1", "u2", "u3"));
        approval.put("approveMethod", approveMethod);
        if (approveRatio != null) {
            approval.put("approveRatio", approveRatio);
        }
        approval.put("childNode", Map.of("id", "EndNode", "name", "结束", "type", 1));
        return approval;
    }
}
